baseurl = "/"
DefaultContentLanguage = "en"
title = "Evolve Data Science"
relativeurls = true
theme = "beautifulhugo"
#publishDir = "docs"
metaDataFormat = "yaml"
pygmentsUseClasses = true
pygmentCodeFences = true
disqusShortname = "keithhultman"
googleAnalytics = "UA-88236006-2"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[Params]
  subtitle = "A data science blog by Keith Hultman"
  logo = "img/avatar-icon.png"
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  gcse = "004728632483242462951:s8-btxavfju" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

[[Params.bigimg]]
  src = "img/feature-image-data-blue-short.jpg"
[[Params.bigimg]]
  src = "img/sphere.jpg"
  desc = "Sphere"
[[Params.bigimg]]
  src = "img/hexagon.jpg"


[Author]
  name = "Keith Hultman"
  email = "keithh@gmail.com"
  github = "kahultman"
  twitter = "keithhultman"
  linkedin = "keithhultman"
#  stackoverflow = "users/XXXXXXX/username"
#  youtube = "user/username" # or channel/channelname

[[menu.main]]
    name = "Blog"
    url = ""
    weight = 1

[[menu.main]]
    name = "About"
    url = "page/about/"
    weight = 3

[[menu.main]]
    identifier = "Projects"
    name = "Projects"
    url = "page/"
    weight = 2

[[menu.main]]
    parent = "Projects"
    name = "Divvy Forecasting"
    url = "/post/forecasting-divvy-bikesharing-traffic/"
    weight = 1
    
[[menu.main]]
    parent = "Projects"
    name = "West Nile Virus"
    url = "/post/2016-12-17-wnv-blogpost/"
    weight = 2
    
[[menu.main]]
    parent = "Projects"
    name = "Grupo Bimbo"
    url = "/post/grupo-bimbo-report/"
    weight = 3
    
[[menu.main]]
    parent = "Projects"
    name = "Meteor Data Exploration"
    url = "/post/2015-09-07-meteor"
    weight = 4
    
[[menu.main]]
    identifier = "Blogroll"
    name = "Blogroll"
    url = "page/blogroll"
    weight = 4
    
[[menu.main]]
    parent = "Blogroll"
    name = "R-bloggers"
    url = "https://www.r-bloggers.com/"
    weight = 1

[[menu.main]]
    name = "Tags"
    url = "tags"
    weight = 3

